#!/usr/bin/env bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Ensure database schema is up-to-date
"
}

function migrate() {
    docker compose up -d database
    docker compose \
        -f docker-compose.yml \
        -f docker-compose.migrations.yml \
        run --rm migration "$@"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        echo "Running migrations"
        migrate "$@"
    fi
fi
